/** Storybook story IDs and viewport widths for visual regression */
export const canvasStories = [
  { id: "style-guide-colors--canvas", name: "style-guide-colors", width: 1200 },
  { id: "style-guide-color-tokens--canvas", name: "style-guide-color-tokens", width: 1064 },
  { id: "style-guide-typography--canvas", name: "style-guide-typography", width: 1064 },
  { id: "style-guide-buttons--canvas", name: "style-guide-buttons", width: 808 },
  { id: "style-guide-raise-levels--canvas", name: "style-guide-raise-levels", width: 760 },
  {
    id: "components-buttons--canvas",
    name: "components-buttons",
    width: 526,
    clipSelector: "[data-figma-buttons-grid]",
  },
  { id: "components-icons--canvas", name: "components-icons", width: 774 },
  { id: "components-core--canvas", name: "components-core", width: 732 },
  { id: "components-illustrations--canvas", name: "components-illustrations", width: 1152 },
  { id: "components-sidebar--canvas", name: "components-sidebar", width: 464 },
  { id: "components-sidebar-layouts--canvas", name: "components-sidebar-layouts", width: 1200 },
  { id: "components-chat--canvas", name: "components-chat", width: 1200 },
  { id: "components-ships--canvas", name: "components-ships", width: 1280 },
  { id: "components-content--canvas", name: "components-content", width: 1280 },
  { id: "components-forms--canvas", name: "components-forms", width: 564 },
  { id: "components-report--canvas", name: "components-report", width: 770 },
  { id: "components-modals--canvas", name: "components-modals", width: 1200 },
  { id: "components-skeletons--canvas", name: "components-skeletons", width: 512 },
  { id: "components-report-layout--canvas", name: "components-report-layout", width: 960 },
  { id: "components-search--canvas", name: "components-search", width: 848 },
  { id: "components-settings--canvas", name: "components-settings", width: 1076 },
  { id: "components-workflows--canvas", name: "components-workflows", width: 1200 },
  { id: "components-domain-forms--canvas", name: "components-domain-forms", width: 1200 },
  { id: "components-filters--canvas", name: "components-filters", width: 1232 },
  { id: "components-library--canvas", name: "components-library", width: 1288 },
] as const;
