/** Semantic design tokens mapped to CSS custom properties */
export const semanticTokens = {
  action: {
    primary: {
      idle: "var(--action-primary-idle)",
      onIdle: "var(--action-primary-on-idle)",
      hover: "var(--action-primary-hover)",
      onHover: "var(--action-primary-on-hover)",
      disabled: "var(--action-primary-disabled)",
      onDisabled: "var(--action-primary-on-disabled)",
    },
    secondary: {
      idle: "var(--action-secondary-idle)",
      onIdle: "var(--action-secondary-on-idle)",
      hover: "var(--action-secondary-hover)",
      onHover: "var(--action-secondary-on-hover)",
      disabled: "var(--action-secondary-disabled)",
      onDisabled: "var(--action-secondary-on-disabled)",
    },
    tertiary: {
      idle: "var(--action-tertiary-idle)",
      onIdle: "var(--action-tertiary-on-idle)",
      hover: "var(--action-tertiary-hover)",
      onHover: "var(--action-tertiary-on-hover)",
      disabled: "var(--action-tertiary-disabled)",
      onDisabled: "var(--action-tertiary-on-disabled)",
    },
    quaternary: {
      idle: "var(--action-quaternary-idle)",
      onIdle: "var(--action-quaternary-on-idle)",
      hover: "var(--action-quaternary-hover)",
      onHover: "var(--action-quaternary-on-hover)",
      disabled: "var(--action-quaternary-disabled)",
      onDisabled: "var(--action-quaternary-on-disabled)",
    },
    destructive: {
      idle: "var(--action-destructive-idle)",
      onIdle: "var(--action-destructive-on-idle)",
      hover: "var(--action-destructive-hover)",
      onHover: "var(--action-destructive-on-hover)",
      disabled: "var(--action-destructive-disabled)",
      onDisabled: "var(--action-destructive-on-disabled)",
    },
  },
  background: {
    primary: "var(--background-primary)",
    secondary: "var(--background-secondary)",
    tertiary: "var(--background-tertiary)",
    hover: "var(--background-hover)",
    selected: "var(--background-selected)",
    overlay: "var(--background-overlay)",
  },
  display: {
    onLight: {
      primary: "var(--display-on-light-primary)",
      secondary: "var(--display-on-light-secondary)",
      tertiary: "var(--display-on-light-tertiary)",
      quaternary: "var(--display-on-light-quaternary)",
    },
    onDark: {
      primary: "var(--display-on-dark-primary)",
      secondary: "var(--display-on-dark-secondary)",
      tertiary: "var(--display-on-dark-tertiary)",
      quaternary: "var(--display-on-dark-quaternary)",
    },
  },
  accent: {
    onLight: "var(--accent-on-light)",
    onDark: "var(--accent-on-dark)",
    bgLight: "var(--accent-bg-light)",
    bgLighter: "var(--accent-bg-lighter)",
  },
  divider: {
    primary: "var(--divider-primary)",
    secondary: "var(--divider-secondary)",
  },
  meta: {
    green: "var(--meta-green)",
    onGreen: "var(--meta-on-green)",
    orange: "var(--meta-orange)",
    onOrange: "var(--meta-on-orange)",
    red: "var(--meta-red)",
    onRed: "var(--meta-on-red)",
    blue: "var(--meta-blue)",
    onBlue: "var(--meta-on-blue)",
    purple: "var(--meta-purple)",
    onPurple: "var(--meta-on-purple)",
  },
} as const;
