export const theme = {
  fontFamily: {
    sans: ["Work Sans", "sans-serif"],
    mono: ["Roboto Mono", "monospace"],
    signature: ["Alex Brush", "Lucida Handwriting", "cursive"],
  },
  fontSize: {
    subheader: [
      "18px",
      {
        lineHeight: "28px",
        letterSpacing: "-0.01em",
      },
    ],
    "subheader-em": [
      "18px",
      {
        lineHeight: "28px",
        letterSpacing: "-0.01em",
        fontWeight: "500",
      },
    ],
    body: [
      "16px",
      {
        lineHeight: "28px",
        letterSpacing: "-0.01em",
      },
    ],
    "body-em": [
      "16px",
      {
        lineHeight: "28px",
        letterSpacing: "-0.01em",
        fontWeight: "500",
      },
    ],
    "caption-1": [
      "16px",
      {
        lineHeight: "22px",
      },
    ],
    "caption-1-em": [
      "16px",
      {
        lineHeight: "22px",
        fontWeight: "500",
      },
    ],
    "caption-2": [
      "14px",
      {
        lineHeight: "20px",
      },
    ],
    "caption-2-em": [
      "14px",
      {
        lineHeight: "20px",
        fontWeight: "500",
      },
    ],
    footnote: [
      "13px",
      {
        lineHeight: "17px",
      },
    ],
    "footnote-em": [
      "13px",
      {
        lineHeight: "17px",
        fontWeight: "500",
      },
    ],
  },
  width: {
    authPageWidth: "370px",
  },
  keyframes: {
    "accordion-down": {
      from: { height: 0 },
      to: { height: "var(--radix-accordion-content-height)" },
    },
    "accordion-up": {
      from: { height: "var(--radix-accordion-content-height)" },
      to: { height: 0 },
    },
  },
  animation: {
    "accordion-down": "accordion-down 0.2s ease-out",
    "accordion-up": "accordion-up 0.2s ease-out",
  },
  colors: {
    brand: {
      50: "#e0fff2",
      100: "#adf0d3",
      200: "#8aeac1",
      300: "#67e4ae",
      400: "#45de9c",
      500: "#26d489",
      600: "#1da56a",
      700: "#15754c",
      800: "#0c452d",
      900: "#04160e",
    },
    gray: {
      50: "#fafafa",
      100: "#f0f0f0",
      200: "#d6d6d6",
      300: "#bdbdbd",
      400: "#a3a3a3",
      500: "#8a8a8a",
      600: "#6e6e6e",
      700: "#525252",
      800: "#363636",
      900: "#1a1a1a",
    },
    green: {
      50: "#e0fff2",
      100: "#adf0d3",
      200: "#8aeac1",
      300: "#67e4ae",
      400: "#45de9c",
      500: "#26d489",
      600: "#1da56a",
      700: "#15754c",
      800: "#0c452d",
      900: "#04160e",
    },
    blue: {
      50: "#cae8f7",
      100: "#b8e0f4",
      200: "#95d1ef",
      300: "#71c1ea",
      400: "#4eb2e4",
      500: "#2aa2df",
      600: "#1b82b6",
      700: "#145f85",
      800: "#0d3c54",
      900: "#051923",
    },
    red: {
      50: "#f9dcdc",
      100: "#f6cbcb",
      200: "#f0a8a8",
      300: "#ea8686",
      400: "#e36363",
      500: "#dd4040",
      600: "#c32222",
      700: "#931a1a",
      800: "#641212",
      900: "#340909",
    },
    orange: {
      50: "#fff7eb",
      100: "#f8e0bf",
      200: "#f4cf9a",
      300: "#f0bd75",
      400: "#ecab51",
      500: "#e89a2c",
      600: "#C77C0A",
      700: "#935d10",
      800: "#603d0b",
      900: "#2e1d05",
    },
    "brand-purple": "#ab68ff",
    presentation: "var(--presentation)",
    "text-primary": "var(--text-primary)",
    "text-secondary": "var(--text-secondary)",
    "text-secondary-alt": "var(--text-secondary-alt)",
    "text-tertiary": "var(--text-tertiary)",
    "ring-primary": "var(--ring-primary)",
    "header-primary": "var(--header-primary)",
    "header-hover": "var(--header-hover)",
    "header-button-hover": "var(--header-button-hover)",
    "surface-active": "var(--surface-active)",
    "surface-active-alt": "var(--surface-active-alt)",
    "surface-hover": "var(--surface-hover)",
    "surface-primary": "var(--surface-primary)",
    "surface-primary-alt": "var(--surface-primary-alt)",
    "surface-primary-contrast": "var(--surface-primary-contrast)",
    "surface-secondary": "var(--surface-secondary)",
    "surface-secondary-alt": "var(--surface-secondary-alt)",
    "surface-tertiary": "var(--surface-tertiary)",
    "surface-tertiary-alt": "var(--surface-tertiary-alt)",
    "surface-dialog": "var(--surface-dialog)",
    "surface-submit": "var(--surface-submit)",
    "border-light": "var(--border-light)",
    "border-medium": "var(--border-medium)",
    "border-medium-alt": "var(--border-medium-alt)",
    "border-heavy": "var(--border-heavy)",
    "border-xheavy": "var(--border-xheavy)",
    border: "hsl(var(--border))",
    input: "hsl(var(--input))",
    ["switch-unchecked"]: "hsl(var(--switch-unchecked))",
    ring: "hsl(var(--ring))",
    background: "hsl(var(--background))",
    foreground: "hsl(var(--foreground))",
    primary: {
      DEFAULT: "hsl(var(--primary))",
      foreground: "hsl(var(--primary-foreground))",
    },
    secondary: {
      DEFAULT: "hsl(var(--secondary))",
      foreground: "hsl(var(--secondary-foreground))",
    },
    destructive: {
      DEFAULT: "hsl(var(--destructive))",
      foreground: "hsl(var(--destructive-foreground))",
    },
    muted: {
      DEFAULT: "hsl(var(--muted))",
      foreground: "hsl(var(--muted-foreground))",
    },
    accent: {
      DEFAULT: "hsl(var(--accent))",
      foreground: "hsl(var(--accent-foreground))",
    },
    card: {
      DEFAULT: "hsl(var(--card))",
      foreground: "hsl(var(--card-foreground))",
    },
  },
  borderRadius: {
    lg: "8px",
    md: "calc(8px - 2px)",
    sm: "calc(8px - 4px)",
  },
};
